<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Thalis Rebouças">
  <title>Análise da Série de Consumo de Energia Elétrica no Ceará</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-595329fc85a7a1c59bec09a8ca20da1e.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section class="quarto-title-block center">
  <h1 class="title">Análise da Série de Consumo de Energia Elétrica no Ceará</h1>
  <p class="subtitle">CC0308 - 2025 | Julho 2025 <br><br> Slides:<strong>https://thalisreboucas.github.io/Analise-da-Serie-EPE-CE/#/</strong></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Thalis Rebouças 
</div>
</div>
</div>

</section>
<section class="slide level2">
<h2>Sumário de aprendizagem</h2>
<div style="font-size: 80%;">
<ul>
<li><p>Resumo Geral</p>
<ol type="1">
<li><p>Motivo da Escolha da Série</p></li>
<li><p>Apresentação da Série</p></li>
</ol></li>
<li><p>Estimação dos Modelos de Série Temporal</p>
<ol start="3" type="1">
<li><p>Método de Suavização Exponencial</p></li>
<li><p>Metodologia Box-Jenkins</p></li>
<li><p>Análise de Intervenções</p></li>
</ol></li>
<li><p>Conclusão</p>
<ol start="7" type="1">
<li><p>Conclusão das análises e modelos</p></li>
<li><p>Referências</p></li>
</ol></li>
</ul>
</div>
</section>
<section class="title-slide slide level1 center">
<h1>Vamos lá!</h1>

</section>

<section>
<section class="title-slide slide level1 center">
<h1>Motivo da Escolha da Série</h1>

</section>
<section class="slide level2">
<h2>Motivo da <br> Escolha da Série:</h2>
<p><strong>Qual série ?</strong></p>
<p><span class="math display">\[Z_t = \text{Consumo Mensal de Energia Elétrica no Ceará (Sistema Simples) (2004-2025)}\]</span></p>
<!--# Descrito por hugo -->
<p><strong>Por que Análisar ?</strong></p>
<ul>
<li><p>Identificar padrões e tendências no consumo energético.</p></li>
<li><p>Apoiar políticas públicas para eficiência energética.</p></li>
<li><p>Entender como fatores como o cresimento da população e sazonalidade influenciam o consumo.</p></li>
</ul>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Apresentação da série.</h1>

</section>
<section class="slide level2">
<h2>Apresentação da série:</h2>
<ul>
<li><p>É uma série do EPE(Empresa de Pesquisa Energética) do Ministério de Minas e Energia (MME).</p></li>
<li><p>É um dado público disponível desde de 2004 de todos os estados e tipo de consumo <a href="https://www.epe.gov.br/_layouts/download.aspx?sourceURL=%2Fsites-pt%2Fpublicacoes-dados-abertos%2Fpublicacoes%2FDocuments%2FCONSUMO%2520MENSAL%2520DE%2520ENERGIA%2520EL%25c3%2589TRICA%2520POR%2520CLASSE.xlsx">neste link</a>.</p></li>
</ul>
<p>Neste caso, vou me restringir a análisar apenas o consumo do Ceará na parte de consumo de energia elétrica na rede (MWh) de Sistema Simples.</p>
<ul>
<li>É possivél entender melhor os dados e análises que o governo faz <a href="https://encurtador.com.br/6qoRG">neste link</a>.</li>
</ul>
</section>
<section class="slide level2">
<h2>Apresentação da série:</h2>
<div style="font-size: 70%;">
<p>A série começa em janeiro de 2004 e vai até março de 2025,com isso tem cerca de 255 observações,vamos olhar o <strong>gráfico da série:</strong></p>
</div>

<img data-src="index_files/figure-revealjs/unnamed-chunk-1-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section class="slide level2">
<h2>Apresentação da série:</h2>
<p>Fazendo o gráfico box-plot separados por mês,quadrimestre e ano.</p>

<img data-src="index_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Percebemos um aumento nos últimos meses do ano e valores de outliers em alguns anos.</p>
</section>
<section class="slide level2">
<h2>Divisão da Série:</h2>
<p><strong>Fazendo a divisão da série em teste e treino</strong></p>
<p>Será feita um divisão na série em teste e treino, onde:</p>
<ul>
<li><p>A série de treino vai até o final do ano de 2022</p></li>
<li><p>A série de teste começa do ano de 2023 até março de 2025</p></li>
</ul>
<p>Assim sendo um divisão de 27 observações a serem prevista nos teste dos modelos</p>
<pre><code># A série começa em Janeiro de 2004
ts_ceara &lt;- ts(ceara_data$consumo_gwh, start = c(2004, 1), frequency = 12)
# 2. Criar o conjunto de TREINO usando a função window()
treino &lt;- window(ts_ceara, end = c(2022, 12))
# 3. Criar o conjunto de TESTE usando a função window()
teste &lt;- window(ts_ceara, start = c(2023, 1), end = c(2025, 3))</code></pre>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Método de Suavização Exponencial</h1>

</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<p>Passo a passo:</p>
<ul>
<li>A metodologia de suavização exponencial foi aplicada usando a função ets() do R.</li>
</ul>
<p>Esta função testa diferentes combinações de componentes de Erro (E), Tendência (T) e Sazonalidade (S), selecionando o modelo que minimiza um critério de informação, como o AIC (Critério de Informação de Akaike).</p>
<p>O modelo é ajustado apenas com o conjunto de treino, será selecionado apenas o que tiver o melhor AIC definido pela a função do <code>ETS()</code> do <strong>R</strong>.</p>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<p>Fazendo a utilização da chamada do modelo temos:</p>
<pre><code>modelo_ets &lt;- ets(treino)
</code></pre>
<ul>
<li>Que o melhor modelo sugerido foi o ETS(M,Ad,M)</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Componente</th>
<th>Tipo</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Erro (E)</strong></td>
<td>M: Multiplicativo</td>
<td>A variabilidade aumenta com o nível da série</td>
</tr>
<tr class="even">
<td><strong>Tendência (T)</strong></td>
<td>Ad: Aditiva Damping</td>
<td>Tendência aditiva com amortecimento (freia ao longo do tempo)</td>
</tr>
<tr class="odd">
<td><strong>Sazonalidade (S)</strong></td>
<td>M: Multiplicativa</td>
<td>Sazonalidade proporcional ao nível da série</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<ul>
<li>Formula do Modelo:</li>
</ul>
<p><span class="math display">\[\begin{align*}
\textbf{Previsão:} \quad
\hat{y}_{t+h} &amp;= (l_t + \phi^h b_t) \cdot s_{t+h-m(k+1)} \\[1em]

\textbf{Atualização do nível:} \quad
l_t &amp;= \alpha \cdot \frac{y_t}{s_{t-m}} + (1 - \alpha)(l_{t-1} + \phi b_{t-1}) \\[1em]

\textbf{Atualização da tendência:} \quad
b_t &amp;= \beta \cdot (l_t - l_{t-1}) + (1 - \beta) \cdot \phi b_{t-1} \\[1em]

\textbf{Atualização da sazonalidade:} \quad
s_t &amp;= \gamma \cdot \frac{y_t}{l_t} + (1 - \gamma) \cdot s_{t-m}
\end{align*}\]</span></p>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<pre><code>summary(modelo_ets)
</code></pre>
<ul>
<li><p>Modelo selecionado pelo melhor AIC</p></li>
<li><p><strong>Alpha (nível):</strong> <span class="math inline">\(\alpha = 0,7001\)</span></p></li>
<li><p><strong>Beta (tendência):</strong> <span class="math inline">\(\beta = 0,0038\)</span></p></li>
<li><p><strong>Gamma (sazonalidade):</strong> <span class="math inline">\(\gamma = 0,0001\)</span></p></li>
<li><p><strong>Damping:</strong> <span class="math inline">\(\phi = 0,9787\)</span></p></li>
<li><p><strong>Nível inicial:</strong> <span class="math inline">\(l_0 = 506720,43\)</span></p></li>
<li><p><strong>Tendência inicial:</strong> <span class="math inline">\(b_0 = 3288,48\)</span></p></li>
<li><p><strong>Desvio Padrão dos erros:</strong> <span class="math inline">\(0,0313\)</span></p></li>
<li><p><strong>AIC:</strong> <span class="math inline">\(5878,418\)</span></p></li>
</ul>
<p><strong>Sazonalidade inicial:</strong> <span class="math inline">\(s_1 = 1,033, \ldots, s_{12} = 1,0149\)</span></p>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<p><strong>Métricas de desempenho no conjunto de treino:</strong></p>
<ul>
<li><p>RMSE: 26.608,53</p></li>
<li><p>MAE: 19.550,13</p></li>
<li><p>MAPE: 2,29% ⇒ Erro percentual muito baixo</p></li>
<li><p>ACF dos resíduos: 0,066 ⇒ Baixa autocorrelação</p></li>
</ul>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<ul>
<li>Formula do modelo</li>
</ul>
<p><span class="math display">\[\begin{align*}
\hat{y}_{t+h} &amp;= \left( 506720{,}43 + 0{,}9787^h \cdot 3288{,}48 \right) \cdot s_{t+h-12(k+1)} \\
l_t &amp;= 0{,}7001 \cdot \frac{y_t}{s_{t-12}} + (1 - 0{,}7001)(l_{t-1} + 0{,}9787 \cdot b_{t-1}) \\
b_t &amp;= 0{,}0038 \cdot (l_t - l_{t-1}) + (1 - 0{,}0038) \cdot 0{,}9787 \cdot b_{t-1} \\
s_t &amp;= 0{,}0001 \cdot \frac{y_t}{l_t} + (1 - 0{,}0001) \cdot s_{t-12}
\end{align*}\]</span></p>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><ul>
<li><p>Modelo quase ajustado</p></li>
<li><p>Captura tendência suavizada e sazonalidade proporcional fraca</p></li>
<li><p>Resíduos sem padrão aparente</p></li>
</ul>
</section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section class="slide level2">
<h2>Método de Suavização Exponencial</h2>
<ul>
<li>Acurácia do Modelo ETS no Conjunto de Teste</li>
</ul>
<pre><code>print(acuracia_ets)</code></pre>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE       MPE     MAPE      MASE
Training set  2256.726 26608.53 19550.13 0.2166755 2.290358 0.4268799
Test set     56980.434 68775.69 59854.76 4.8439823 5.115651 1.3069370
                   ACF1 Theil's U
Training set 0.06585039        NA
Test set     0.25875513  1.389201</code></pre>
</div>
</div>
<p>O modelo apresenta um desempenho ruim no conjunto de teste. Embora tenha se ajustado razoavelmente bem aos dados de treinamento, ele não conseguiu generalizar essa performance para os dados futuros (o conjunto de teste).</p>
<p>O modelo está superajustado (overfit) e tem um desempenho de previsão muito ruim, sendo inferior a um método de benchmark simples.</p>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Metodologia Box-Jenkins</h1>

</section>
<section class="slide level2">
<h2>Metodologia Box-Jenkins</h2>
<p>Uma abordagem sistemática para análise e previsão de Séries Temporais</p>
<p><strong>Modelo Central: ARIMA(p, d, q)</strong></p>
<p>O objetivo é encontrar o modelo que melhor se ajusta aos dados.</p>
<ul>
<li><strong>AR (p): Autoregressivo</strong>
<ul>
<li>Dependência dos <strong>valores passados</strong> da própria série.</li>
</ul></li>
<li><strong>I (d): Integrado</strong>
<ul>
<li>Número de <strong>diferenciações</strong> necessárias para tornar a série estacionária.</li>
</ul></li>
<li><strong>MA (q): Média Móvel</strong>
<ul>
<li>Dependência dos <strong>erros de previsão passados</strong>.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">
<h2>Metodologia Box-Jenkins</h2>
<div style="font-size: 70%;">
<p><strong>Processo Iterativo em 4 Etapas</strong></p>
<ol type="1">
<li><strong>Identificação do Modelo</strong>
<ul>
<li>Verificar e ajustar a <strong>estacionariedade</strong> da série (usando diferenciação <code>d</code>).</li>
<li>Analisar gráficos de <strong>Autocorrelação (FAC)</strong> e <strong>Autocorrelação Parcial (FACP)</strong> para sugerir as ordens <code>p</code> e <code>q</code>.</li>
</ul></li>
<li><strong>Estimação dos Parâmetros</strong>
<ul>
<li>Calcular os coeficientes do modelo ARIMA(p, d, q) candidato.</li>
</ul></li>
<li><strong>Verificação de Diagnóstico</strong>
<ul>
<li>Analisar os <strong>resíduos</strong> do modelo: eles devem se comportar como ruído branco (aleatórios e sem padrão).</li>
<li>Se o modelo for inadequado, retorna-se à Etapa 1.</li>
</ul></li>
<li><strong>Previsão</strong>
<ul>
<li>Com um modelo validado, utilizá-lo para prever valores futuros.</li>
</ul></li>
</ol>
<p><strong>Pontos-Chave</strong></p>
<ul>
<li><strong>Guiado pelos Dados:</strong> A estrutura do modelo é definida pelos padrões encontrados nos próprios dados.</li>
<li><strong>Iterativo:</strong> É um ciclo de identificação, ajuste e verificação.</li>
<li><strong>Objetivo:</strong> Construir um modelo estatisticamente robusto para gerar previsões precisas.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<p>Podemos decompor a serie para ver a sazonalidade e estacionáridade,</p>

<img data-src="index_files/figure-revealjs/unnamed-chunk-8-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p><strong>Percebe-se um tendência práticamente linear cresente e uma série serrote, vamos olhar os lags para ver se tem tendência.</strong></p>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<pre><code>adf.test(treino) 
kpss.test(treino) 
</code></pre>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  treino
Dickey-Fuller = -3.1698, Lag order = 6, p-value = 0.09388
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  treino
KPSS Level = 4.4547, Truncation lag parameter = 4, p-value = 0.01</code></pre>
</div>
</div>
<div style="font-size: 70%;">
<p>Com base nos resultados dos testes, a sua série temporal <code>treino</code> <strong>não é estacionária</strong>.</p>
<p>Ambos os testes, apesar de terem hipóteses opostas, apontam para a mesma conclusão.</p>
<hr>
<p><strong>Teste Augmented Dickey-Fuller (ADF)</strong></p>
<p>O teste ADF busca evidências de que a série <em>é estacionária</em>.</p>
<ul>
<li><strong>Hipótese Nula (<span class="math inline">\(H_0\)</span>)</strong>: A série <strong>não é estacionária</strong> (possui raiz unitária).</li>
<li><strong>Seu resultado</strong>: O p-valor foi de <strong>0.09388</strong>.</li>
</ul>
<p>Como o p-valor (0.09) é <strong>maior</strong> que o nível de significância padrão (0.05), você <strong>falha em rejeitar</strong> a hipótese nula. Isso significa que, segundo o teste ADF, a série é considerada <strong>não estacionária</strong>.</p>
<hr>
<p><strong>Teste KPSS</strong></p>
<p>O teste KPSS, por outro lado, busca evidências de que a série <em>não é estacionária</em>.</p>
<ul>
<li><strong>Hipótese Nula (<span class="math inline">\(H_0\)</span>)</strong>: A série <strong>é estacionária</strong>.</li>
<li><strong>Seu resultado</strong>: O p-valor foi de <strong>0.01</strong>.</li>
</ul>
<p>Como o p-valor (0.01) é <strong>menor</strong> que o nível de significância (0.05), você <strong>rejeita</strong> a hipótese nula. Isso significa que o teste KPSS também conclui que a série é <strong>não estacionária</strong>.</p>
<p><strong>Conclusão Final</strong></p>
<p>Ambos os testes confirmam que a série <code>treino</code> <strong>não é estacionária</strong>. O próximo passo na modelagem ARIMA seria aplicar a <strong>diferenciação</strong> na série para tentar torná-la estacionária. 👍</p>
</div>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<p>Análisando os lags da série:</p>
<pre><code>gerar_diagnostico_ts(ts_ceara)</code></pre>

<img data-src="index_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Temos um forte evidência do modelo ser um autoregressivo de ordem 1 ou 2 e que a parte de médias móveis precisa tem um tratamento para aparecer, mesmo que no limte um sazonalidade no lag 12 ~ 14.</p>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<p>Análisando os dados da Série da <strong>primeira diferança</strong>:</p>
<pre><code>ts_diff= diff(ts_ceara)
gerar_diagnostico2_ts(ts_diff)
adf.test(ts_diff)
kpss.test(ts_diff)</code></pre>

<img data-src="index_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<p><strong>Principais Observações</strong></p>
<ul>
<li><p><strong>Estacionariedade:</strong> A série se tornou estacionária após <strong>1 diferenciação</strong> (<code>d=1</code>).</p></li>
<li><p><strong>Sazonalidade Anual:</strong> Padrão sazonal muito forte, com “spikes” significativos nos <strong>lags 12 e 24</strong> nos gráficos ACF e PACF.</p>
<ul>
<li>O spike claro no <strong>PACF</strong> no lag 12 sugere um componente <strong>AR Sazonal (P=1)</strong>.</li>
</ul></li>
<li><p><strong>Componente Não-Sazonal:</strong> O <strong>PACF</strong> corta abruptamente após o lag 1.</p>
<ul>
<li>Isso sugere um componente <strong>AR(1) (p=1)</strong>.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<div style="font-size: 60%;">
<p><strong>Modelo Proposto Inicial: <span class="math inline">\(SARIMA(1, 1, 1)(1, 0,0)^{12}\)</span></strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 38%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Componente</th>
<th style="text-align: center;">Ordem</th>
<th style="text-align: left;">Justificativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>p</strong> (AR Não-sazonal)</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Corte no PACF no lag 1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>d</strong> (Diferenciação)</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Aplicada para obter estacionariedade</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>q</strong> (MA Não-sazonal)</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Ponto de partida simples</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>P</strong> (AR Sazonal)</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Spike significativo no PACF no lag 12</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>D</strong> (Dif. Sazonal)</td>
<td style="text-align: center;"><strong>0</strong></td>
<td style="text-align: left;">Não parece necessária a primeira vista</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Q</strong> (MA Sazonal)</td>
<td style="text-align: center;"><strong>0</strong></td>
<td style="text-align: left;">Ponto de partida simples</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>s</strong> (Período Sazonal)</td>
<td style="text-align: center;"><strong>12</strong></td>
<td style="text-align: left;">Padrão anual</td>
</tr>
</tbody>
</table>
<p>temos uma melhora da série e os testes de Dickey-Fuller e KPSS deu que a série é estacionaria.</p>
</div>
<p>Os testes de Dickey-Fuller e KPSS deu que a série é estacionaria.</p>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 1</h2>
<div style="font-size: 60%;">
<p>A fórmula é:</p>
<p><span class="math inline">\(SARIMA(1, 1, 1)(1, 0, 0)_{12}\)</span></p>
<h3>Detalhamento dos Componentes</h3>
<ul>
<li><strong>SARIMA</strong>: Sigla para <em>Seasonal AutoRegressive Integrated Moving Average</em>.</li>
<li><strong>(p, d, q) = (1, 0, 1)</strong>: Esta é a parte <strong>não sazonal</strong> do modelo.
<ul>
<li><code>p=1</code>: Um termo autorregressivo (AR).</li>
<li><code>d=0</code>: Uma diferenciação regular para tornar a série estacionária.</li>
<li><code>q=1</code>: Nenhum termo de média móvel (MA).</li>
</ul></li>
<li><strong>(P, D, Q)m = (1, 0, 0)m</strong>: Esta é a parte <strong>sazonal</strong> do modelo.
<ul>
<li><code>P=1</code>: Um termo autorregressivo sazonal.</li>
<li><code>D=0</code>: Nenhuma diferenciação sazonal.</li>
<li><code>Q=0</code>: Nenhum termo de média móvel sazonal.</li>
<li><code>m</code>: Representa o período da sazonalidade (por exemplo, <code>m=12</code> para dados mensais).</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 1</h2>
<pre><code>Modelo1 &lt;- Arima(treino, order = c(1, 1, 1), seasonal = c(1,0,0))

summary(Modelo1)</code></pre>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: treino 
ARIMA(1,1,1)(1,0,0)[12] 

Coefficients:
         ar1      ma1    sar1
      0.7196  -0.8920  0.2938
s.e.  0.0688   0.0378  0.0687

sigma^2 = 885243577:  log likelihood = -2659.45
AIC=5326.89   AICc=5327.07   BIC=5340.59

Training set error measures:
                   ME    RMSE      MAE       MPE     MAPE      MASE        ACF1
Training set 4622.065 29490.9 22057.06 0.5171221 2.607869 0.4816191 -0.01643013</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 1</h2>
<p>Equação Proposta 1: <span class="math display">\[(1 - \phi_1 B)(1 - \Phi_1 B^{12})(1-B) Y_t = (1 + \Theta_1 B) a_t\]</span></p>
<p>Substiduindo os valores obtidos, temos:</p>
<p><span class="math display">\[
(1 - 0,7196 B)(1 - 0,2938B^{12})(1-B)Y_t = (1 -0.8920 B) a_t
\]</span></p>
</section>
<section class="slide level2">
<h2>Diagnóstico Modelo 1</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-13-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Os gráficos indicam que os resíduos do modelo se comportam como ruído branco, sem autocorrelação, sugerindo um bom ajuste,mas que pode ser melhorado.</p>
</section>
<section class="slide level2">
<h2>Sugestão de outro Modelo</h2>
</section>
<section class="slide level2">
<h2>Análises Primárias da série e Ajustes:</h2>
<p>Análisando os dados da Série da <strong>primeira diferança normal e uma sazonal</strong>:</p>
<pre><code>
ts_diff_12 = diff(diff(ts_ceara),12)
gerar_diagnostico2_ts(ts_diff_12 )
adf.test(ts_diff_12)
kpss.test(ts_diff_12)</code></pre>

<img data-src="index_files/figure-revealjs/unnamed-chunk-14-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section class="slide level2">
<h2>Sugestão Modelo 2</h2>
<div style="font-size: 60%;">
<p>A fórmula é:</p>
<p><span class="math inline">\(SARIMA(1, 1, 1)(1, 1, 1)_{12}\)</span></p>
<h3>Detalhamento dos Componentes</h3>
<ul>
<li><strong>SARIMA</strong>: Sigla para <em>Seasonal AutoRegressive Integrated Moving Average</em>.</li>
<li><strong>(p, d, q) = (1, 0, 1)</strong>: Esta é a parte <strong>não sazonal</strong> do modelo.
<ul>
<li><code>p=1</code>: Um termo autorregressivo (AR).</li>
<li><code>d=1</code>: Uma diferenciação regular para tornar a série estacionária.</li>
<li><code>q=1</code>: Uma termo de média móvel (MA).</li>
</ul></li>
<li><strong>(P, D, Q)m = (1, 0, 0)m</strong>: Esta é a parte <strong>sazonal</strong> do modelo.
<ul>
<li><code>P=1</code>: Um termo autorregressivo sazonal.</li>
<li><code>D=1</code>: Um diferenciação sazonal.</li>
<li><code>Q=1</code>: Um termo de média móvel sazonal.</li>
<li><code>m</code>: Representa o período da sazonalidade (por exemplo, <code>m=12</code> para dados mensais).</li>
</ul></li>
</ul>
</div>
<p><span class="math display">\[
(1 - \phi_1 B)(1 - \Phi_1 B^{12})(1-B)(1-B^{12}) Y_t = (1 + \theta_1 B)(1 + \Theta_1 B^{12}) a_t
\]</span></p>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 2</h2>
<pre><code>Modelo2 &lt;- Arima(treino, order = c(1, 1, 1), seasonal = c(1,1,1))

summary(Modelo2)</code></pre>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: treino 
ARIMA(1,1,1)(1,1,1)[12] 

Coefficients:
         ar1      ma1    sar1     sma1
      0.6463  -0.9003  0.0834  -0.9975
s.e.  0.0744   0.0409  0.0738   0.2232

sigma^2 = 726899456:  log likelihood = -2513.46
AIC=5036.91   AICc=5037.2   BIC=5053.76

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -895.7818 25936.48 18829.75 -0.1492058 2.178924 0.4111503
                    ACF1
Training set -0.02809811</code></pre>
</div>
</div>
<div style="font-size: 60%;">
<p>O modelo SARIMA(1,1,1)(1,1,1)[12] apresenta um excelente ajuste aos dados de treinamento, com resíduos que se comportam como ruído branco. No entanto, o modelo é ligeiramente mais complexo do que o necessário, pois um de seus coeficientes não é estatisticamente significativo, sugerindo que uma versão simplificada seria mais adequada (parcimoniosa)</p>
</div>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 2</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-16-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><div style="font-size: 60%;">
<p>Gráfico da Série: Os resíduos flutuam aleatoriamente em torno de zero, sem qualquer tendência ou padrão visível.</p>
<p>ACF e PACF: Os gráficos de autocorrelação e autocorrelação parcial mostram que praticamente todos os lags estão dentro dos limites de significância (linhas azuis). Isso indica que não há autocorrelação remanescente, um forte sinal de que os resíduos se comportam como ruído branco.</p>
</div>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 2</h2>
<p>Assim esse é o Modelo sugerido ideal ao meu ver, <span class="math display">\[(1 - 0.6463 B)(1 - 0.0834 B^{12})(1-B)(1-B^{12}) Y_t = \]</span> <span class="math display">\[(1 - 0.9003 B)(1 - 0.9975 B^{12}) a_t\]</span></p>
</section>
<section class="slide level2">
<h2>Sugestão Modelo 2</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-17-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Modelo Final</h1>

</section>
<section class="slide level2">
<h2>Sugestão Modelo Final</h2>
<p>o Ajuste para um modelo final foi removido o termo não significativo sar1. O novo candidato, que deve ser o modelo final é o SARIMA(1,1,1)(0,1,1)[12]</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: treino 
ARIMA(1,1,1)(1,1,1)[12] 

Coefficients:
         ar1      ma1    sar1     sma1
      0.6463  -0.9003  0.0834  -0.9975
s.e.  0.0744   0.0409  0.0738   0.2232

sigma^2 = 726899456:  log likelihood = -2513.46
AIC=5036.91   AICc=5037.2   BIC=5053.76

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -895.7818 25936.48 18829.75 -0.1492058 2.178924 0.4111503
                    ACF1
Training set -0.02809811</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Sugestão Modelo Final</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Sugestão Modelo Final</h2>
<p>Este modelo SARIMA(1,1,1)(0,1,1)[12] é a versão otimizada e final. Ele é mais simples, todos os seus componentes são significativos, e ele se ajusta melhor aos dados segundo os critérios de informação. O próximo passo é usar este modelo para fazer previsões e avaliar seu desempenho no conjunto de teste.</p>
<p><span class="math display">\[
(1 - 0.6370 B)(1-B)(1-B^{12}) Y_t = (1 - 0.8923 B)(1 - 0.9166 B^{12}) a_t
\]</span></p>
</section>
<section class="slide level2">
<h2>Previsão Modelo final</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section></section>
<section class="title-slide slide level1 center">
<h1>Análise de Intervenções</h1>
<pre><code>detectAO(Modelo3)
detectIO(Modelo3)</code></pre>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "No AO detected"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]
ind     196.000000
lambda1  -4.841556</code></pre>
</div>
</div>
<div style="font-size: 60%;">
<p>Este resultado indica que o algoritmo de detecção de outliers encontrou um evento estatisticamente significativo na sua série temporal.</p>
<ul>
<li><p><strong>Evento Detectado:</strong> Um outlier significativo foi identificado no <strong>ponto de índice 196</strong> da série .</p></li>
<li><p><strong>Tipo de Outlier:</strong> A mensagem <code>"No AO detected"</code> informa que não foram encontrados Outliers Aditivos (pontos isolados atípicos). Portanto, o outlier encontrado no índice 196 é de outro tipo, muito provavelmente uma <strong>Mudança de Nível (Level Shift - LS)</strong>.</p></li>
<li><p><strong>Significância e Impacto:</strong> O valor <code>lambda1</code> (<code>-4.84</code>) é a estatística-t do evento. Por ser um valor alto (em módulo), o outlier é <strong>altamente significativo</strong>. O sinal negativo indica que houve uma <strong>queda abrupta e permanente</strong> no nível médio da série a partir do ponto 196.</p></li>
</ul>
<p><strong>Em resumo:</strong> a análise sugere que algo mudou estruturalmente na série no 196º período que é maio de 2020, causando uma queda em seu patamar. Isso deve ser incorporado ao modelo final para melhorar a precisão das previsões.</p>
</div>
</section>

<section class="title-slide slide level1 center">
<h1>Análise de Intervenções</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: treino 
Regression with ARIMA(1,1,1)(0,1,1)[12] errors 

Coefficients:
         ar1      ma1     sma1       xreg
      0.6219  -0.8848  -0.9295  -64822.33
s.e.  0.0793   0.0447   0.1088   21815.90

sigma^2 = 734106319:  log likelihood = -2509.59
AIC=5029.19   AICc=5029.47   BIC=5046.04

Training set error measures:
                   ME     RMSE      MAE        MPE     MAPE      MASE
Training set -850.648 26064.73 19178.95 -0.1455986 2.219304 0.4187752
                    ACF1
Training set -0.02008813</code></pre>
</div>
</div>
<div style="font-size: 50%;">
<p>O modelo combina uma regressão linear com um modelo <strong>SARIMA <code>(1,1,1)(0,1,1)[12]</code></strong> para capturar a dinâmica dos erros, o que é uma abordagem poderosa.</p>
<ul>
<li><strong>Coeficientes Significativos:</strong> Todos os coeficientes, incluindo o da variável externa (<code>xreg</code>), são estatisticamente significativos. Isso indica que a variável <code>xreg</code> contribui de forma importante para a previsão.</li>
<li><strong>Boa Acurácia:</strong> O erro percentual absoluto médio (<strong>MAPE</strong>) de <strong>2.22%</strong> é geralmente considerado um bom nível de precisão.</li>
<li><strong>Resíduos Limpos:</strong> O valor de <strong>ACF1</strong> (-0.02) é muito próximo de zero, sugerindo que não há autocorrelação remanescente nos resíduos. Isso é um forte indicativo de que a estrutura do modelo capturou bem os padrões dos dados.</li>
</ul>
</div>
</section>

<section>
<section class="title-slide slide level1 center">
<h1>Análise de Intervenções</h1>
<p>Fazendo agora o Gráfico de Previsão com a Interveção colocada</p>

<img data-src="index_files/figure-revealjs/unnamed-chunk-24-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Modelo Final</h2>
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Componente</th>
<th style="text-align: left;">Termo na Equação</th>
<th style="text-align: left;">Valor/Parâmetro Estimado</th>
<th style="text-align: left;">Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Autorregressivo (AR)</strong></td>
<td style="text-align: left;"><code>(1 - 0.6219 B)</code></td>
<td style="text-align: left;"><code>φ₁ = 0.6219</code></td>
<td style="text-align: left;">Modela a dependência do valor atual com o do período anterior (memória de curto prazo).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Média Móvel (MA)</strong></td>
<td style="text-align: left;"><code>(1 - 0.8848 B)</code></td>
<td style="text-align: left;"><code>θ₁ = -0.8848</code></td>
<td style="text-align: left;">Modela a dependência do valor atual com o erro de previsão do período anterior.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Média Móvel Sazonal</strong></td>
<td style="text-align: left;"><code>(1 - 0.9295 B¹²)</code></td>
<td style="text-align: left;"><code>Θ₁ = -0.9295</code></td>
<td style="text-align: left;">Modela a dependência com o erro de previsão do mesmo mês no ano anterior.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Diferenciação</strong></td>
<td style="text-align: left;"><code>(1 - B)(1 - B¹²)</code></td>
<td style="text-align: left;">N/A (Operadores)</td>
<td style="text-align: left;">Remove a tendência e a sazonalidade para tornar a série estacionária.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Efeito da Intervenção</strong></td>
<td style="text-align: left;"><code>-64822.33 * ... * P_t</code></td>
<td style="text-align: left;"><code>ω = -64822.33</code></td>
<td style="text-align: left;">O impacto imediato do evento, causando uma queda de ~64.8k unidades.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Erro Aleatório</strong></td>
<td style="text-align: left;"><code>a_t</code></td>
<td style="text-align: left;">N/A (Variável)</td>
<td style="text-align: left;">Flutuações imprevisíveis restantes após a modelagem dos outros componentes.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">
<h2>Modelo Final</h2>
<p>Esta é a equação do modelo final com intervenção, com os valores estimados a partir dos dados.</p>
<p>O coeficiente <strong>-64822.33</strong> (<code>ω</code>) representa o <strong>impacto imediato e pontual</strong> do evento de intervenção (no tempo <span class="math inline">\(T\)</span>). Isso significa que, no momento em que ocorreu, o evento causou uma <strong>queda estimada de aproximadamente 64.822 unidades</strong> no nível da série.</p>
<p>Os outros coeficientes (<code>ar1=0.6219</code>, <code>ma1=-0.8848</code>, <code>sma1=-0.9295</code>) definem a “memória” da série, ou seja, como o efeito desse choque inicial e de outras flutuações aleatórias se dissipam e se propagam ao longo dos meses seguintes.</p>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Conclusão das análises e modelos</h1>

</section>
<section class="slide level2">
<h2>Conclusão das análises e modelos</h2>
<div style="font-size: 60%;">
<p>Avaliamos quatro modelos de duas famílias principais: <strong>ARIMA</strong> e <strong>ETS</strong>.</p>
<ol type="1">
<li><strong>Regressão com Erros ARIMA (Dinâmico)</strong>
<ul>
<li><code>Regression with ARIMA(1,1,1)(0,1,1)[12] errors</code></li>
<li>Inclui uma variável externa (<code>xreg</code>) para melhorar a previsão.</li>
</ul></li>
<li><strong>ARIMA Sazonal (SARIMA)</strong>
<ul>
<li><code>ARIMA(1,1,1)(0,1,1)[12]</code></li>
</ul></li>
<li><strong>ARIMA Sazonal (Alternativo)</strong>
<ul>
<li><code>ARIMA(1,1,1)(1,0,0)[12]</code></li>
</ul></li>
<li><strong>ETS (Suavização Exponencial)</strong>
<ul>
<li><code>ETS(M,Ad,M)</code> - (Erro Multiplicativo, Tendência Aditiva Amortecida, Sazonalidade Multiplicativa)</li>
</ul></li>
</ol>
<section class="slide level2">
<h2>Conclusão das análises e modelos</h2>
<h3><strong>Qualidade do Ajuste vs.&nbsp;Complexidade</strong></h3>
<ul>
<li><strong>AIC, AICc, BIC:</strong> Penalizam modelos complexos para evitar sobreajuste.</li>
<li><strong><em>Quanto menor, melhor.</em></strong></li>
</ul>
<h4><strong>Acurácia da Previsão (no treino)</strong></h4>
<ul>
<li><strong>RMSE, MAE, MAPE:</strong> Medem o erro médio das previsões.</li>
<li><strong><em>Quanto menor, melhor.</em></strong></li>
</ul>
</section>
</div>
</section>
<section class="slide level2">
<h2>Resultados: Qualidade do Ajuste</h2>
<p>Comparamos os critérios de informação. Valores mais baixos indicam um melhor equilíbrio entre o ajuste do modelo e sua simplicidade.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: left;">AIC</th>
<th style="text-align: left;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Reg-ARIMA</strong> 🏆</td>
<td style="text-align: left;"><strong>5029.19</strong></td>
<td style="text-align: left;"><strong>5046.04</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA (0,1,1)[12]</td>
<td style="text-align: left;">5035.95</td>
<td style="text-align: left;">5049.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ARIMA (1,0,0)[12]</td>
<td style="text-align: left;">5326.89</td>
<td style="text-align: left;">5340.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">ETS(M,Ad,M)</td>
<td style="text-align: left;">5878.42</td>
<td style="text-align: left;">5940.15</td>
</tr>
</tbody>
</table>
<p><strong>Conclusão:</strong> O modelo <strong>Regressão com Erros ARIMA</strong> se mostra superior, sugerindo que a variável externa (<code>xreg</code>) adiciona valor real.</p>
</section>
<section class="slide level2">
<h2>Resultados: Acurácia da Previsão</h2>
<p>Analisamos os erros de previsão no conjunto de dados de treino.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;">MAE</th>
<th style="text-align: left;">MAPE (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Reg-ARIMA</strong> 🏆</td>
<td style="text-align: left;"><strong>26064.73</strong></td>
<td style="text-align: left;"><strong>19178.95</strong></td>
<td style="text-align: left;"><strong>2.22%</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA (0,1,1)[12]</td>
<td style="text-align: left;">26697.04</td>
<td style="text-align: left;">19381.64</td>
<td style="text-align: left;">2.24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ARIMA (1,0,0)[12]</td>
<td style="text-align: left;">29490.90</td>
<td style="text-align: left;">22057.06</td>
<td style="text-align: left;">2.61%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ETS(M,Ad,M)</td>
<td style="text-align: left;">26608.53</td>
<td style="text-align: left;">19550.13</td>
<td style="text-align: left;">2.29%</td>
</tr>
</tbody>
</table>
<p><strong>Conclusão:</strong> O <strong>Reg-ARIMA</strong> consistentemente produz os menores erros, confirmando sua maior precisão.</p>
</section>
<section class="slide level2">
<h2>O Veredito: O Modelo Vencedor</h2>
<p>O modelo <strong>Regressão com Erros ARIMA(1,1,1)(0,1,1)[12]</strong> é a escolha recomendada.</p>
<h3>Por que ele venceu?</h3>
<ul>
<li>✅ <strong>Menores Critérios de Informação (AIC &amp; BIC):</strong> Melhor equilíbrio entre ajuste e complexidade.</li>
<li>✅ <strong>Menores Erros de Previsão (RMSE &amp; MAE):</strong> Previsões mais acuradas.</li>
<li>✅ <strong>Poder Explicativo Adicional:</strong> A variável externa <code>xreg</code> é estatisticamente significativa e melhora o desempenho do modelo em relação a um ARIMA puro.</li>
</ul>
</section></section>
<section class="title-slide slide level1 center">
<h1>Referências Teóricas</h1>
<ul>
<li><p>Box, G. E. P., Jenkins, G. M., Reinsel, G. C., &amp; Ljung, G. M., <em>Time Series Analysis: Forecasting and Control</em> (Wiley Series in Probability and Statistics), 5th Edition.</p></li>
<li><p>Brockwell, P. J., &amp; Davis, R. A., <em>Time Series: Theory and Methods</em> (Springer Series in Statistics), 2nd Edition.</p></li>
<li><p>Hamilton, J. D., <em>Time Series Analysis</em> (Princeton University Press), 1st Edition.</p></li>
<li><p>Morettin, P. A., &amp; Toloi, C. M. C., <em>Séries Temporais em R: Análise e Previsão</em> (Blucher), 1st Edition.</p></li>
<li><p>Shumway, R. H., &amp; Stoffer, D. S., <em>Time Series Analysis and Its Applications: With R Examples</em> (Springer Texts in Statistics), 4th Edition.</p></li>
</ul>
</section>

<section class="title-slide slide level1 center">
<h1>Obrigado !!</h1>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Slides por Thalis Rebouças, feito em <a href="https://quarto.org/docs/presentations/revealjs/index.html">Quarto</a>. Código disponível <a href="https://github.com/thalisreboucas/Analise-da-Serie-EPE-CE">no GitHub</a>.</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>